
# This file was *autogenerated* from the file hello.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_7 = Integer(7)
from sage.all import *

print inverse_mod(_sage_const_3 ,_sage_const_7 )

